### ISSUE TITLE
dockerfile fails to build

### ISSUE THREAD

**Issue by foobarbecue** [USGS-Astrogeology/AstroWebMaps#3]
Wanted to have a go at running PILOT locally and seeing if I can tweak it. Saw there's a dockerfile and tried to build an image with `docker build`. It gets to step 7/11 and fails with:

```
Step 7/11 : COPY docker/php.ini.d/ $PHP_INI_DIR/conf.d/
COPY failed: file not found in build context or excluded by .dockerignore: stat docker/php.ini.d/: file does not exist
```

Is this the expected behavior?

**Comment by jlaura** [comment]
@mbailen Looks like you pushed the Dockerfile. Any thoughts on the error? @thareUSGS can you reproduce locally?

**Comment by mbailen** [comment]
This question should go under PILOT, not Astrowebmaps. I tried reproducing, but couldn't. Not sure why docker isn't seeing that PHP config dir? I sent a message to @evindunn-usgs. He set up the file and may know.

@foobarbecue, you can try commenting out that line and see if PILOT comes up.

**Comment by evindunn** [comment]
@foobarbecue Where are you running `docker build` from? It should build if run from the root of the PILOT repo
```console
docker build -f docker/Dockerfile -t pilot .
```

Let me know how it goes

**Comment by foobarbecue** [comment]
@mbailen oops, thanks, I meant to post to PILOT.

@evindunn Thanks, my problem was that I tried to build while my current path was inside the `docker` directory. Works now!
